version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking AWS CLI version...."
      - aws --version
      - echo "Installing NPM dependencies..."
      - npm install --force

  build:
    commands:
      - echo "Build started on `date`"
      - export NODE_OPTIONS=--max_old_space_size=8192 
      - npm run build
  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - export NODE_OPTIONS=--max_old_space_size=8192
      - aws cloudfront create-invalidation --distribution-id E2Y3G8AHSNNLI1 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
