const studentsGrades = [
  {
    id: 1,
    name: "Aman Dubey",
    section: "Section A",
    group: "Business Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 25,
    score: "80%",
    avatar: "https://avatars.githubusercontent.com/u/109097090?v=4",
  },
  {
    id: 2,
    name: "Emma Johnson",
    section: "Section B",
    group: "Science Group",
    assignment: "380 / 6",
    quizzes: "390 / 6",
    attendance: 28,
    score: "85%",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Mia Brown",
    section: "Section C",
    group: "Arts Group",
    assignment: "420 / 6",
    quizzes: "410 / 6",
    attendance: 22,
    score: "78%",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "Olivia Davis",
    section: "Section D",
    group: "Math Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 30,
    score: "90%",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Liam Martinez",
    section: "Section A",
    group: "Business Group",
    assignment: "350 / 6",
    quizzes: "360 / 6",
    attendance: 20,
    score: "75%",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Noah Wilson",
    section: "Section B",
    group: "Science Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 27,
    score: "88%",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Sophia Anderson",
    section: "Section C",
    group: "Arts Group",
    assignment: "370 / 6",
    quizzes: "380 / 6",
    attendance: 23,
    score: "82%",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "James Lee",
    section: "Section D",
    group: "Math Group",
    assignment: "410 / 6",
    quizzes: "420 / 6",
    attendance: 29,
    score: "92%",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Isabella White",
    section: "Section A",
    group: "Business Group",
    assignment: "380 / 6",
    quizzes: "390 / 6",
    attendance: 21,
    score: "80%",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "William Harris",
    section: "Section B",
    group: "Science Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 25,
    score: "85%",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
  },
];

export default studentsGrades;
