const studentsGrades = [
  {
    id: 1,
    firstName: "Aman",
    lastName: "Dubey",
    section: "Section A",
    group: "Business Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 25,
    score: "80%",
    profile: "https://avatars.githubusercontent.com/u/109097090?v=4",
  },
  {
    id: 2,
    firstName: "Riya",
    lastName: "Sharma",
    section: "Section B",
    group: "Science Group",
    assignment: "350 / 5",
    quizzes: "350 / 5",
    attendance: 27,
    score: "90%",
    profile: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    firstName: "Vikram",
    lastName: "Singh",
    section: "Section A",
    group: "Arts Group",
    assignment: "300 / 4",
    quizzes: "300 / 4",
    attendance: 23,
    score: "75%",
    profile: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Kumar",
    section: "Section C",
    group: "Commerce Group",
    assignment: "380 / 5",
    quizzes: "380 / 5",
    attendance: 28,
    score: "85%",
    profile: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    firstName: "Ankit",
    lastName: "Patel",
    section: "Section B",
    group: "Business Group",
    assignment: "360 / 6",
    quizzes: "360 / 6",
    attendance: 26,
    score: "82%",
    profile: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    firstName: "Neha",
    lastName: "Gupta",
    section: "Section A",
    group: "Science Group",
    assignment: "390 / 6",
    quizzes: "390 / 6",
    attendance: 29,
    score: "88%",
    profile: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    firstName: "Rohan",
    lastName: "Mehta",
    section: "Section C",
    group: "Arts Group",
    assignment: "340 / 5",
    quizzes: "340 / 5",
    attendance: 24,
    score: "77%",
    profile: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    firstName: "Sneha",
    lastName: "Jain",
    section: "Section B",
    group: "Commerce Group",
    assignment: "370 / 5",
    quizzes: "370 / 5",
    attendance: 30,
    score: "92%",
    profile: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    firstName: "Amit",
    lastName: "Chauhan",
    section: "Section A",
    group: "Business Group",
    assignment: "310 / 4",
    quizzes: "310 / 4",
    attendance: 22,
    score: "79%",
    profile: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 10,
    firstName: "Pooja",
    lastName: "Yadav",
    section: "Section C",
    group: "Science Group",
    assignment: "400 / 6",
    quizzes: "400 / 6",
    attendance: 31,
    score: "95%",
    profile: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    firstName: "Raj",
    lastName: "Verma",
    section: "Section B",
    group: "Arts Group",
    assignment: "320 / 5",
    quizzes: "320 / 5",
    attendance: 25,
    score: "80%",
    profile: "https://randomuser.me/api/portraits/men/11.jpg",
  },
];

export default studentsGrades;
