export const classes = [
  {
    className: "Class 1",
    classurl: "Class1",
    teachers: 20,
    students: 250,
    sections: 3,
    groups: 10,
  },
  {
    className: "Class 2",
    classurl: "Class2",
    teachers: 15,
    students: 200,
    sections: 4,
    groups: 8,
  },
  {
    className: "Class 3",
    classurl: "Class3",
    teachers: 22,
    students: 300,
    sections: 5,
    groups: 12,
  },
  {
    className: "Class 4",
    classurl: "Class4",
    teachers: 18,
    students: 220,
    sections: 3,
    groups: 9,
  },
  {
    className: "Class 5",
    classurl: "Class5",
    teachers: 25,
    students: 350,
    sections: 6,
    groups: 15,
  },
  {
    className: "Class 6",
    classurl: "Class6",
    teachers: 17,
    students: 190,
    sections: 2,
    groups: 7,
  },
  {
    className: "Class 7",
    classurl: "Class7",
    teachers: 30,
    students: 400,
    sections: 7,
    groups: 20,
  },
  {
    className: "Class 8",
    classurl: "Class8",
    teachers: 12,
    students: 150,
    sections: 2,
    groups: 5,
  },
  {
    className: "Class 9",
    classurl: "Class9",
    teachers: 20,
    students: 280,
    sections: 4,
    groups: 11,
  },
  {
    className: "Class 10",
    classurl: "Class10",
    teachers: 14,
    students: 180,
    sections: 3,
    groups: 6,
  },
];
