const dummyDiscussionData = [
    {
      id: 1,
      title: "Discussion Next Exam",
      lastPostDate: "10/02/2024",
      lastPostTime: "12:30 PM",
      unreadReplies: 4,
      replies: 2,
    },
    {
      id: 2,
      title: "Project Ideas for Next Semester",
      lastPostDate: "11/03/2024",
      lastPostTime: "01:00 PM",
      unreadReplies: 3,
      replies: 5,
    },
    {
      id: 3,
      title: "Sustainable Development Goals",
      lastPostDate: "12/04/2024",
      lastPostTime: "02:15 PM",
      unreadReplies: 2,
      replies: 7,
    },
    {
      id: 4,
      title: "Machine Learning Trends",
      lastPostDate: "13/05/2024",
      lastPostTime: "03:30 PM",
      unreadReplies: 5,
      replies: 3,
    },
    {
      id: 5,
      title: "Blockchain Technology",
      lastPostDate: "14/06/2024",
      lastPostTime: "04:45 PM",
      unreadReplies: 6,
      replies: 4,
    },
    {
      id: 6,
      title: "AI in Healthcare",
      lastPostDate: "15/07/2024",
      lastPostTime: "05:30 PM",
      unreadReplies: 1,
      replies: 8,
    },
    {
      id: 7,
      title: "Data Science Projects",
      lastPostDate: "16/08/2024",
      lastPostTime: "06:15 PM",
      unreadReplies: 3,
      replies: 6,
    },
    {
      id: 8,
      title: "Next Big Tech Innovations",
      lastPostDate: "17/09/2024",
      lastPostTime: "07:00 PM",
      unreadReplies: 4,
      replies: 5,
    },
    {
      id: 9,
      title: "Ethics in AI",
      lastPostDate: "18/10/2024",
      lastPostTime: "08:30 PM",
      unreadReplies: 2,
      replies: 7,
    },
    {
      id: 10,
      title: "Climate Change Actions",
      lastPostDate: "19/11/2024",
      lastPostTime: "09:45 PM",
      unreadReplies: 5,
      replies: 4,
    },
    {
      id: 11,
      title: "Future of Quantum Computing",
      lastPostDate: "20/12/2024",
      lastPostTime: "10:00 AM",
      unreadReplies: 6,
      replies: 4,
    },
    {
      id: 12,
      title: "Discussion Next Exam",
      lastPostDate: "10/02/2024",
      lastPostTime: "12:30 PM",
      unreadReplies: 4,
      replies: 2,
    },
    {
      id: 13,
      title: "Project Ideas for Next Semester",
      lastPostDate: "11/03/2024",
      lastPostTime: "01:00 PM",
      unreadReplies: 3,
      replies: 5,
    },
    {
      id: 14,
      title: "Sustainable Development Goals",
      lastPostDate: "12/04/2024",
      lastPostTime: "02:15 PM",
      unreadReplies: 2,
      replies: 7,
    },
    {
      id: 15,
      title: "Machine Learning Trends",
      lastPostDate: "13/05/2024",
      lastPostTime: "03:30 PM",
      unreadReplies: 5,
      replies: 3,
    },
    {
      id: 16,
      title: "Blockchain Technology",
      lastPostDate: "14/06/2024",
      lastPostTime: "04:45 PM",
      unreadReplies: 6,
      replies: 4,
    },
    {
      id: 17,
      title: "AI in Healthcare",
      lastPostDate: "15/07/2024",
      lastPostTime: "05:30 PM",
      unreadReplies: 1,
      replies: 8,
    },
    {
      id: 18,
      title: "Data Science Projects",
      lastPostDate: "16/08/2024",
      lastPostTime: "06:15 PM",
      unreadReplies: 3,
      replies: 6,
    },
    {
      id: 19,
      title: "Next Big Tech Innovations",
      lastPostDate: "17/09/2024",
      lastPostTime: "07:00 PM",
      unreadReplies: 4,
      replies: 5,
    },
    {
      id: 20,
      title: "Ethics in AI",
      lastPostDate: "18/10/2024",
      lastPostTime: "08:30 PM",
      unreadReplies: 2,
      replies: 7,
    },
    {
      id: 21,
      title: "Climate Change Actions",
      lastPostDate: "19/11/2024",
      lastPostTime: "09:45 PM",
      unreadReplies: 5,
      replies: 4,
    },
    {
      id: 22,
      title: "Future of Quantum Computing",
      lastPostDate: "20/12/2024",
      lastPostTime: "10:00 AM",
      unreadReplies: 6,
      replies: 3,
    },
    {
      id: 23,
      title: "Space Exploration",
      lastPostDate: "21/01/2025",
      lastPostTime: "11:15 AM",
      unreadReplies: 3,
      replies: 7,
    },
  ];
  
  export default dummyDiscussionData;
  