// src/Components/Admin/Finance/Earnings/Config/formConfig.js

import StationeryFeesForm from "../EarningsForm/StationeryFeesForm";
import OtherFacilityForm from "../EarningsForm/OtherFacilityForm";
import SubscriptionFeesForm from "../EarningsForm/SubscriptionFeesForm";
import WorkshopTrainingFeesForm from "../EarningsForm/WorkshopTrainingFeesForm";
import CanteenProfitForm from "../EarningsForm/CanteenProfitForm";
import RentIncomeForm from "../EarningsForm/RentIncomeForm";
import ExamCenterFeesForm from "../EarningsForm/ExamCenterFeesForm";
import ParkingFeesForm from "../EarningsForm/ParkingFeesForm";
import DonationForm from "../EarningsForm/DonationForm";
import FundraisingForm from "../EarningsForm/FundraisingForm";
import InvestmentForm from "../EarningsForm/InvestmentForm";
// Import other forms as necessary

// Initial values for each subCategory with flat fields
export const initialValuesMap = {
  "Rent Income": {
    name: "",
    startDate: "",
    endDate: "",
    nameOfRenter: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Exam Center Fees": {
    examName: "",
    startDate: "",
    endDate: "",
    mobileNumber: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Parking Fees": {
    vehicleType: "",
    name: "",
    userType: "",
    otherVehicleDetails: "",
    otherUserDetails: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Stationery Fees": {
    stationeryItems: [
      {
        itemName: "",
        quantity: 0,
        unitCost: 0,
      },
    ],
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Other Facility Fees": {
    facilityName: "",
    accessDuration: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Subscription Fees": {
    subscriptionName: "",
    description: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Workshop/Training Fees": {
    sessionTitle: "",
    hostName: "",
    timePeriod: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  "Canteen Profit": {
    periodOfEarnings: "",
    description: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
  },
  Donations: {
    name: "",
    phoneNumber: "",
    address: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
    subCategory: "Donations",
  },
  "Fundraising/Sponsorships": {
    companyName: "",
    phoneNumber: "",
    address: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    receipt: null,
    description: "",
    subCategory: "Fundraising/Sponsorships",
  },
  // Financial Investments SubCategories
  Investments: {
    subCategory: "Investments",
    name: "",
    profitOrLoss: "",
    fromDate: "",
    toDate: "",
    investmentAmount: "",
    returnAmount: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: "",
    paidBy: "Auto",
    advance_amount: "",
    remaining_amount: "",
    tax: "",
    discountType: "percentage",
    discount: "",
    penalty: "",
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: "",
    final_amount: "",
    receipt: null,
    description: "",
  },
  // Repeat for other subCategories with flat fields
};

// Form components mapping
export const formComponentsMap = {
  "Facility-Based Revenue": {
    "Rent Income": <RentIncomeForm />,
    "Exam Center Fees": <ExamCenterFeesForm />,
    "Parking Fees": <ParkingFeesForm />,
    Other: <OtherFacilityForm />, // Adjust based on specific "Other" forms if needed
  },
  "Service-Based Revenue": {
    "Stationery Fees": <StationeryFeesForm />,
    "Other Facility Fees": <OtherFacilityForm />,
    "Subscription Fees": <SubscriptionFeesForm />,
    "Workshop/Training Fees": <WorkshopTrainingFeesForm />,
    "Canteen Profit": <CanteenProfitForm />,
    Other: <OtherFacilityForm />, // Adjust based on specific "Other" forms if needed
  },
  "Community and External Revenue": {
    Donations: <DonationForm />,
    "Fundraising/Sponsorships": <FundraisingForm />,
    Other: <OtherFacilityForm />, // Adjust based on specific "Other" forms if needed
  },
  "Financial Investments": {
    Investments: <InvestmentForm />,
    Other: <OtherFacilityForm />, // Adjust based on specific "Other" forms if needed
  },
  // Add other main categories and their subCategories as necessary
};
