// src/Components/Admin/Finance/Earnings/Config/formConfig.js

import StationeryFeesForm from "../EarningsForm/StationeryFeesForm";
import OtherFacilityForm from "../EarningsForm/OtherFacilityForm";
import SubscriptionFeesForm from "../EarningsForm/SubscriptionFeesForm";
import WorkshopTrainingFeesForm from "../EarningsForm/WorkshopTrainingFeesForm";
import CanteenProfitForm from "../EarningsForm/CanteenProfitForm";
import RentIncomeForm from "../EarningsForm/RentIncomeForm";
import ExamCenterFeesForm from "../EarningsForm/ExamCenterFeesForm";
import ParkingFeesForm from "../EarningsForm/ParkingFeesForm";
import DonationForm from "../EarningsForm/DonationForm";
import FundraisingForm from "../EarningsForm/FundraisingForm";
import InvestmentForm from "../EarningsForm/InvestmentForm";
// Import other forms as necessary

// Initial values for each subCategory with flat fields
export const initialValuesMap = {
  "Rent Income": {
    name: "",
    startDate: "",
    endDate: "",
    nameOfRenter: "",
    payment_type: "cash",
    payment_status: "paid",
    paid_amount: 0,
    paid_by: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discount_type: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Exam Center Fees": {
    examName: "",
    startDate: "",
    endDate: "",
    mobileNumber: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Parking Fees": {
    vehicleType: "",
    name: "",
    userType: "",
    otherVehicleDetails: "",
    otherUserDetails: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Stationery Fees": {
    stationeryItems: [{ itemName: "", quantity: 0, unitCost: 0 }],
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Other Facility Fees": {
    facilityName: "",
    accessDuration: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Subscription Fees": {
    subscriptionName: "",
    description: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Workshop/Training Fees": {
    sessionTitle: "",
    hostName: "",
    timePeriod: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  "Canteen Profit": {
    periodOfEarnings: "",
    description: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
  },
  Donations: {
    name: "",
    phoneNumber: "",
    address: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
    subCategory: "Donations",
  },
  "Fundraising/Sponsorships": {
    companyName: "",
    phoneNumber: "",
    address: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: 0,
    paidBy: "Auto",
    advance_amount: 0,
    remaining_amount: 0,
    tax: 0,
    discountType: "percentage",
    discount: 0,
    penalty: 0,
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: 0,
    final_amount: 0,
    document: "",
    description: "",
    subCategory: "Fundraising/Sponsorships",
  },
  // Financial Investments SubCategories
  Investments: {
    subCategory: "Investments",
    name: "",
    profitOrLoss: "",
    fromDate: "",
    toDate: "",
    investmentAmount: "",
    returnAmount: "",
    paymentType: "cash",
    paymentStatus: "paid",
    paid_amount: "",
    paidBy: "Auto",
    advance_amount: "",
    remaining_amount: "",
    tax: "",
    discountType: "percentage",
    discount: "",
    penalty: "",
    frequencyOfPayment: "Monthly",
    dateTime: "",
    total_amount: "",
    final_amount: "",
    document: "",
    description: "",
  },
  // Repeat for other subCategories with flat fields
};

// Form components mapping
export const formComponentsMap = {
  "Facility-Based Revenue": {
    "Rent Income": RentIncomeForm,
    "Exam Center Fees": ExamCenterFeesForm,
    "Parking Fees": ParkingFeesForm,
    // Add other subCategories as needed
  },
  "Service-Based Revenue": {
    "Stationery Fees": StationeryFeesForm,
    "Other Facility Fees": OtherFacilityForm,
    "Subscription Fees": SubscriptionFeesForm,
    "Workshop/Training Fees": WorkshopTrainingFeesForm,
    "Canteen Profit": CanteenProfitForm,
    // Add other subCategories as needed
  },
  "Community and External Revenue": {
    Donations: DonationForm,
    "Fundraising/Sponsorships": FundraisingForm,
    // Add other subCategories as needed
  },
  "Financial Investments": {
    Investments: InvestmentForm,
    // Add other subCategories as needed
  },
  // Add other main categories and their subCategories as necessary
};
