// formInitialValues.js

export const initialValuesMap = {
  "Student-Based Revenue": {
    studentName: "",
    class: "",
    section: "",
    frequencyOfPayment: "",
    dateTime: "",
    discount: "",
    penalty: "",
    totalAmount: "",
    finalAmount: "",
    paymentStatus: "",
    paidAmount: "",
    paidBy: "",
    paymentType: "",
    chequeNumber: "",
    transactionId: "",
    advanceAmount: "",
    remainingAmount: "",
    receipt: null,
    description: "",
  },
  Donations: {
    name: "",
    phoneNumber: "",
    address: "",
    frequencyOfPayment: "",
    dateTime: "",
    discount: "",
    penalty: "",
    totalAmount: "",
    finalAmount: "",
    paymentStatus: "",
    paidAmount: "",
    paidBy: "",
    paymentType: "",
    chequeNumber: "",
    transactionId: "",
    advanceAmount: "",
    remainingAmount: "",
    receipt: null,
    description: "",
  },
  // Add initial values for other subcategories here
  // Example:
  "Exam Fees": {
    examName: "",
    userOrganisationName: "",
    phoneNumber: "",
    timePeriod: "",
    frequencyOfPayment: "",
    dateTime: "",
    discount: "",
    penalty: "",
    totalAmount: "",
    finalAmount: "",
    paymentStatus: "",
    paidAmount: "",
    paidBy: "",
    paymentType: "",
    chequeNumber: "",
    transactionId: "",
    advanceAmount: "",
    remainingAmount: "",
    receipt: null,
    description: "",
  },
  // Continue adding other subcategories...
};
