export  const books = [
    {
      id: 1,
      title: "Goldfinch",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 10,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 2,
      title: "The Handmaid's Tale",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 10,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 3,
      title: "High Output Management",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 9,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 4,
      title: "Men In A Boat",
      author: "Leslie Alexander",
      category: "Math",
      classLevel: 10,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 5,
      title: "My Book Cover",
      author: "Leslie Alexander",
      category: "History",
      classLevel: 9,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 6,
      title: "In The Company Of Ghosts",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 7,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },

    {
      id: 7,
      title: "In The Company Of Ghosts",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 7,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },

    {
      id: 8,
      title: "In The Company Of Ghosts",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 7,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },

    {
      id: 9,
      title: "In The Company Of Ghosts",
      author: "Leslie Alexander",
      category: "Business Management",
      classLevel: 7,
      copies: 500,
      available: 350,
      coverImageUrl:
        "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ];

  export const bookIssueData = [
    {
      id: 1,
      studentName: "Arlene McCoy",
      classSection: "10 - B",
      bookTitle: "Goldfinch",
      author: "Leslie Alexander",
      issueDate: "02/10/2024",
      dueDate: "06/10/2024",
      status: "Pending",
      classLevel: "10",
      section: "B",
      category: "Business Management",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 2,
      studentName: "Albert Flores",
      classSection: "10 - B",
      bookTitle: "The Handmaid's Tale",
      author: "Leslie Alexander",
      issueDate: "02/10/2024",
      dueDate: "06/10/2024",
      status: "Return",
      classLevel: "10",
      section: "B",
      category: "Business Management",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 3,
      studentName: "Eleanor Pena",
      classSection: "11 - A",
      bookTitle: "To Kill a Mockingbird",
      author: "Harper Lee",
      issueDate: "03/10/2024",
      dueDate: "07/10/2024",
      status: "Pending",
      classLevel: "11",
      section: "A",
      category: "Literature",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 4,
      studentName: "Darlene Robertson",
      classSection: "12 - C",
      bookTitle: "1984",
      author: "George Orwell",
      issueDate: "01/10/2024",
      dueDate: "05/10/2024",
      status: "Return",
      classLevel: "12",
      section: "C",
      category: "Science Fiction",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 5,
      studentName: "Ronald Richards",
      classSection: "9 - D",
      bookTitle: "Moby Dick",
      author: "Herman Melville",
      issueDate: "04/10/2024",
      dueDate: "08/10/2024",
      status: "Pending",
      classLevel: "9",
      section: "D",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 6,
      studentName: "Savannah Nguyen",
      classSection: "11 - B",
      bookTitle: "Pride and Prejudice",
      author: "Jane Austen",
      issueDate: "05/10/2024",
      dueDate: "09/10/2024",
      status: "Pending",
      classLevel: "11",
      section: "B",
      category: "Literature",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 7,
      studentName: "Francisco Alexander",
      classSection: "10 - A",
      bookTitle: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      issueDate: "06/10/2024",
      dueDate: "10/10/2024",
      status: "Pending",
      classLevel: "10",
      section: "A",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 8,
      studentName: "Wade Warren",
      classSection: "12 - A",
      bookTitle: "Jane Eyre",
      author: "Charlotte Brontë",
      issueDate: "07/10/2024",
      dueDate: "11/10/2024",
      status: "Return",
      classLevel: "12",
      section: "A",
      category: "Literature",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 9,
      studentName: "Marvin McKinney",
      classSection: "10 - D",
      bookTitle: "War and Peace",
      author: "Leo Tolstoy",
      issueDate: "08/10/2024",
      dueDate: "12/10/2024",
      status: "Pending",
      classLevel: "10",
      section: "D",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 10,
      studentName: "Cameron Williamson",
      classSection: "9 - B",
      bookTitle: "The Catcher in the Rye",
      author: "J.D. Salinger",
      issueDate: "09/10/2024",
      dueDate: "13/10/2024",
      status: "Return",
      classLevel: "9",
      section: "B",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 11,
      studentName: "Esther Howard",
      classSection: "11 - C",
      bookTitle: "Frankenstein",
      author: "Mary Shelley",
      issueDate: "10/10/2024",
      dueDate: "14/10/2024",
      status: "Pending",
      classLevel: "11",
      section: "C",
      category: "Science Fiction",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 12,
      studentName: "Jerome Bell",
      classSection: "12 - B",
      bookTitle: "The Odyssey",
      author: "Homer",
      issueDate: "11/10/2024",
      dueDate: "15/10/2024",
      status: "Return",
      classLevel: "12",
      section: "B",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 13,
      studentName: "Kathryn Murphy",
      classSection: "10 - C",
      bookTitle: "Brave New World",
      author: "Aldous Huxley",
      issueDate: "12/10/2024",
      dueDate: "16/10/2024",
      status: "Pending",
      classLevel: "10",
      section: "C",
      category: "Science Fiction",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 14,
      studentName: "Ethan Brown",
      classSection: "9 - A",
      bookTitle: "Wuthering Heights",
      author: "Emily Brontë",
      issueDate: "13/10/2024",
      dueDate: "17/10/2024",
      status: "Return",
      classLevel: "9",
      section: "A",
      category: "Literature",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 15,
      studentName: "Victoria Ortiz",
      classSection: "11 - D",
      bookTitle: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      issueDate: "14/10/2024",
      dueDate: "18/10/2024",
      status: "Pending",
      classLevel: "11",
      section: "D",
      category: "Fantasy",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 16,
      studentName: "Jacob Jones",
      classSection: "12 - D",
      bookTitle: "The Hobbit",
      author: "J.R.R. Tolkien",
      issueDate: "15/10/2024",
      dueDate: "19/10/2024",
      status: "Return",
      classLevel: "12",
      section: "D",
      category: "Fantasy",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 17,
      studentName: "Brooklyn Simmons",
      classSection: "10 - A",
      bookTitle: "A Tale of Two Cities",
      author: "Charles Dickens",
      issueDate: "16/10/2024",
      dueDate: "20/10/2024",
      status: "Pending",
      classLevel: "10",
      section: "A",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 18,
      studentName: "Aiden Nguyen",
      classSection: "9 - C",
      bookTitle: "Great Expectations",
      author: "Charles Dickens",
      issueDate: "17/10/2024",
      dueDate: "21/10/2024",
      status: "Return",
      classLevel: "9",
      section: "C",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 19,
      studentName: "Liam Martinez",
      classSection: "11 - A",
      bookTitle: "Fahrenheit 451",
      author: "Ray Bradbury",
      issueDate: "18/10/2024",
      dueDate: "22/10/2024",
      status: "Pending",
      classLevel: "11",
      section: "A",
      category: "Science Fiction",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 20,
      studentName: "Avery Davis",
      classSection: "12 - C",
      bookTitle: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      issueDate: "19/10/2024",
      dueDate: "23/10/2024",
      status: "Paid",
      classLevel: "12",
      section: "C",
      category: "Classics",
      image: "https://via.placeholder.com/40",
    },
  ];

  export const dummyData = [
    {
      id: 1,
      name: "Leslie Alexander",
      class: "09",
      section: "B",
      feesType: "Final Exam Fees",
      dueDate: "01/10/2024",
      amount: "100 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 2,
      name: "Eleanor Pena",
      class: "10",
      section: "A",
      feesType: "Admission Fees",
      dueDate: "01/10/2024",
      amount: "100 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 3,
      name: "Michael Johnson",
      class: "11",
      section: "C",
      feesType: "Sports Fees",
      dueDate: "15/09/2024",
      amount: "150 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 4,
      name: "James Smith",
      class: "08",
      section: "D",
      feesType: "Library Fees",
      dueDate: "10/10/2024",
      amount: "50 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 5,
      name: "Patricia Williams",
      class: "09",
      section: "A",
      feesType: "Tuition Fees",
      dueDate: "20/09/2024",
      amount: "500 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 6,
      name: "Jennifer Brown",
      class: "10",
      section: "B",
      feesType: "Lab Fees",
      dueDate: "25/09/2024",
      amount: "200 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 7,
      name: "Linda Davis",
      class: "11",
      section: "A",
      feesType: "Final Exam Fees",
      dueDate: "01/10/2024",
      amount: "100 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 8,
      name: "Barbara Miller",
      class: "08",
      section: "C",
      feesType: "Admission Fees",
      dueDate: "15/10/2024",
      amount: "100 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 9,
      name: "Richard Wilson",
      class: "09",
      section: "D",
      feesType: "Sports Fees",
      dueDate: "20/10/2024",
      amount: "150 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 10,
      name: "Joseph Moore",
      class: "10",
      section: "A",
      feesType: "Library Fees",
      dueDate: "25/10/2024",
      amount: "50 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 11,
      name: "Thomas Anderson",
      class: "11",
      section: "B",
      feesType: "Tuition Fees",
      dueDate: "30/09/2024",
      amount: "500 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 12,
      name: "Christopher Taylor",
      class: "08",
      section: "A",
      feesType: "Lab Fees",
      dueDate: "05/10/2024",
      amount: "200 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 13,
      name: "Daniel Thomas",
      class: "09",
      section: "C",
      feesType: "Final Exam Fees",
      dueDate: "10/10/2024",
      amount: "100 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 14,
      name: "Matthew Jackson",
      class: "10",
      section: "D",
      feesType: "Admission Fees",
      dueDate: "15/10/2024",
      amount: "100 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 15,
      name: "Anthony White",
      class: "11",
      section: "A",
      feesType: "Sports Fees",
      dueDate: "20/10/2024",
      amount: "150 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 16,
      name: "Donald Harris",
      class: "08",
      section: "B",
      feesType: "Library Fees",
      dueDate: "25/10/2024",
      amount: "50 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 17,
      name: "Mark Martin",
      class: "09",
      section: "D",
      feesType: "Tuition Fees",
      dueDate: "30/09/2024",
      amount: "500 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 18,
      name: "Paul Martinez",
      class: "10",
      section: "C",
      feesType: "Lab Fees",
      dueDate: "05/10/2024",
      amount: "200 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 19,
      name: "Steven Robinson",
      class: "11",
      section: "A",
      feesType: "Final Exam Fees",
      dueDate: "10/10/2024",
      amount: "100 QR",
      status: "Paid",
      image: "https://via.placeholder.com/40",
    },
    {
      id: 20,
      name: "Kenneth Clark",
      class: "08",
      section: "B",
      feesType: "Admission Fees",
      dueDate: "15/10/2024",
      amount: "100 QR",
      status: "Unpaid",
      image: "https://via.placeholder.com/40",
    },
  ];
  