export const notices = [
    {
      id: 1,
      title: 'Administrative Notices',
      date: 'July 25, 2024',
      priority: 'High Priority',
      content: 'Information related to academic activities such as examination schedules, important deadlines for submission of assignments, and updates on curriculum changes. It also includes notifications about administrative procedures and protocols, ensuring that all academic and administrative operations run smoothly. Additionally, students and staff will find announcements regarding upcoming meetings, events, and other critical academic functions that are essential for maintaining the academic integrity and administrative efficiency of the institution.',
      imageUrl: 'https://www.adobe.com/content/dam/www/us/en/events/overview-page/eventshub_evergreen_opengraph_1200x630_2x.jpg'
    },
    {
      id: 2,
      title: 'Administrative Notices',
      date: 'July 26, 2024',
      priority: 'Low Priority',
      content: 'Updates on administrative procedures including new guidelines for staff and faculty, modifications to existing protocols, and other administrative changes. This notice serves to keep the academic community informed about procedural adjustments that impact daily operations. It ensures that everyone is aware of new administrative practices, helping to streamline processes and maintain organizational efficiency within the institution. The updates are aimed at improving administrative workflows and ensuring compliance with institutional policies.',
      imageUrl: 'https://www.adobe.com/content/dam/www/us/en/events/overview-page/eventshub_evergreen_opengraph_1200x630_2x.jpg'
    },
    {
      id: 3,
      title: 'Administrative Notices',
      date: 'July 26, 2024',
      priority: 'Low Priority',
      content: 'Updates on administrative procedures including new guidelines for staff and faculty, modifications to existing protocols, and other administrative changes. This notice serves to keep the academic community informed about procedural adjustments that impact daily operations. It ensures that everyone is aware of new administrative practices, helping to streamline processes and maintain organizational efficiency within the institution. The updates are aimed at improving administrative workflows and ensuring compliance with institutional policies.',
      imageUrl: 'https://www.adobe.com/content/dam/www/us/en/events/overview-page/eventshub_evergreen_opengraph_1200x630_2x.jpg'
    },
    {
      id: 4,
      title: 'Administrative Notices',
      date: 'July 26, 2024',
      priority: 'Low Priority',
      content: 'Updates on administrative procedures including new guidelines for staff and faculty, modifications to existing protocols, and other administrative changes. This notice serves to keep the academic community informed about procedural adjustments that impact daily operations. It ensures that everyone is aware of new administrative practices, helping to streamline processes and maintain organizational efficiency within the institution. The updates are aimed at improving administrative workflows and ensuring compliance with institutional policies.',
      imageUrl: 'https://www.adobe.com/content/dam/www/us/en/events/overview-page/eventshub_evergreen_opengraph_1200x630_2x.jpg'
    }
    // More notices can be added similarly
  ];

 export  const studentFinanceDummyData = {
    finance: {
        totalUnpaidFees: 2500,
        parentsAccountTotalPaid: 3500,
        totalPaidFees: 5500,
        myAccountPaidFees: 6500,
        feesDetails: [
            {
                feeType: "Final Exam Fees",
                paidBy: "Parents",
                dueDate: "2024-10-21",
                amount: 200,
                status: "Unpaid",
            },
            {
                feeType: "Final Exam Fees",
                paidBy: "Student",
                dueDate: "2024-08-15",
                amount: 800,
                status: "Unpaid",
            },
            {
                feeType: "Final Exam Fees",
                paidBy: "Parents",
                dueDate: "2024-08-15",
                amount: 100,
                status: "Paid",
            },
            {
                feeType: "Sports Fees",
                paidBy: "Parents",
                dueDate: "2024-08-15",
                amount: 300,
                status: "Paid",
            },
        ],
    },
};

export const schedulerData = [
  {
    startDate: new Date(2024,5, 6, 9, 30), // March 2, 2024, 9:30 AM
    endDate: new Date(2024, 5, 6, 11, 30), // March 2, 2024, 11:30 AM
    title: "Founder Meet at Hall   ",
    id: 1,
    type: "College Holiday",
    location: "School grounds",
    director: "Abul Kasem Khan",
    details: "Lorem Ipsum is simply dummy text of psum is simply dummy text of thpsum is simply dummy text of thpsum is simply dummy text of thpsum is simply dummy text of ththe printing and typesetting industry.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnR8ZW58MHx8MHx8fDA%3D", // Example placeholder image
    students: [
      { photo: "https://via.placeholder.com/40", name: "Student 1" },
      { photo: "https://via.placeholder.com/40", name: "Student 2" },
      // More students...
    ]
  },
  {
    startDate: new Date(2024, 2, 5, 10, 0), // March 5, 2024, 10:00 AM
    endDate: new Date(2024, 2, 5, 12, 0), // March 5, 2024, 12:00 PM
    title: "Spring Cultural at the National university ",
    id: 2,
    type: "Cultural Event",
    location: "Auditorium",
    director: "Ayesha Rahman",
    details: "An event showcasing cultural performances and exhibitions.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnR8ZW58MHx8MHx8fDA%3D", // Example placeholder image
    students: [
      { photo: "https://via.placeholder.com/40", name: "Student 3" },
      { photo: "https://via.placeholder.com/40", name: "Student 4" },
      // More students...
    ]
  },
  {
    startDate: new Date(2024, 2, 10, 14, 0), // March 10, 2024, 2:00 PM
    endDate: new Date(2024, 2, 10, 16, 0), // March 10, 2024, 4:00 PM
    title: "Science Fair",
    id: 3,
    type: "Educational Event",
    location: "Science Block",
    director: "Dr. Ahmed Hossain",
    details: "Students showcase their science projects and experiments.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnR8ZW58MHx8MHx8fDA%3D", // Example placeholder image
    students: [
      { photo: "https://via.placeholder.com/40", name: "Student 5" },
      { photo: "https://via.placeholder.com/40", name: "Student 6" },
      // More students...
    ]
  },
  {
    startDate: new Date(2024, 2, 15, 9, 0), // March 15, 2024, 9:00 AM
    endDate: new Date(2024, 2, 15, 11, 0), // March 15, 2024, 11:00 AM
    title: "Art Exhibition",
    id: 4,
    type: "Exhibition",
    location: "Art Gallery",
    director: "Sarah Islam",
    details: "Display of artworks by students and local artists.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnR8ZW58MHx8MHx8fDA%3D", // Example placeholder image
    students: [
      { photo: "https://via.placeholder.com/40", name: "Student 7" },
      { photo: "https://via.placeholder.com/40", name: "Student 8" },
      // More students...
    ]
  },
  {
    startDate: new Date(2024, 2, 20, 13, 0), // March 20, 2024, 1:00 PM
    endDate: new Date(2024, 2, 20, 15, 0), // March 20, 2024, 3:00 PM
    title: "Music Concert",
    id: 5,
    type: "Concert",
    location: "Main Hall",
    director: "Rashidul Karim",
    details: "An evening of musical performances by students and guest artists.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnR8ZW58MHx8MHx8fDA%3D", // Example placeholder image
    students: [
      { photo: "https://via.placeholder.com/40", name: "Student 9" },
      { photo: "https://via.placeholder.com/40", name: "Student 10" },
      // More students...
    ]
  },
  
];  

export const books = [
  {
    id: 1,
    title: "Goldfinch",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 10,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 2,
    title: "The Handmaid's Tale",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 10,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 3,
    title: "High Output Management",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 9,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 4,
    title: "Men In A Boat",
    author: "Leslie Alexander",
    category: "Math",
    classLevel: 10,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 5,
    title: "My Book Cover",
    author: "Leslie Alexander",
    category: "History",
    classLevel: 9,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 6,
    title: "In The Company Of Ghosts",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 7,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 7,
    title: "In The Company Of Ghosts",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 7,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 8,
    title: "In The Company Of Ghosts",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 7,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
  {
    id: 9,
    title: "In The Company Of Ghosts",
    author: "Leslie Alexander",
    category: "Business Management",
    classLevel: 7,
    copies: 500,
    available: 350,
    coverImageUrl:
      "https://mockuptree.com/wp-content/uploads/edd/2024/03/Book-cover-mockup-minimal-960x640.jpg",
  },
];
export const bookIssueData = [
  {
    id: 1,
    studentName: "Arlene McCoy",
    classSection: "10 - B",
    bookTitle: "Goldfinch",
    author: "Leslie Alexander",
    issueDate: "02/10/2024",
    dueDate: "06/10/2024",
    status: "Pending",
    classLevel: "10",
    section: "B",
    category: "Business Management",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 2,
    studentName: "Albert Flores",
    classSection: "10 - B",
    bookTitle: "The Handmaid's Tale",
    author: "Leslie Alexander",
    issueDate: "02/10/2024",
    dueDate: "06/10/2024",
    status: "Return",
    classLevel: "10",
    section: "B",
    category: "Business Management",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 3,
    studentName: "Eleanor Pena",
    classSection: "11 - A",
    bookTitle: "To Kill a Mockingbird",
    author: "Harper Lee",
    issueDate: "03/10/2024",
    dueDate: "07/10/2024",
    status: "Pending",
    classLevel: "11",
    section: "A",
    category: "Literature",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 4,
    studentName: "Darlene Robertson",
    classSection: "12 - C",
    bookTitle: "1984",
    author: "George Orwell",
    issueDate: "01/10/2024",
    dueDate: "05/10/2024",
    status: "Return",
    classLevel: "12",
    section: "C",
    category: "Science Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 5,
    studentName: "Ronald Richards",
    classSection: "9 - D",
    bookTitle: "Moby Dick",
    author: "Herman Melville",
    issueDate: "04/10/2024",
    dueDate: "08/10/2024",
    status: "Pending",
    classLevel: "9",
    section: "D",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 6,
    studentName: "Savannah Nguyen",
    classSection: "11 - B",
    bookTitle: "Pride and Prejudice",
    author: "Jane Austen",
    issueDate: "05/10/2024",
    dueDate: "09/10/2024",
    status: "Pending",
    classLevel: "11",
    section: "B",
    category: "Literature",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 7,
    studentName: "Francisco Alexander",
    classSection: "10 - A",
    bookTitle: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    issueDate: "06/10/2024",
    dueDate: "10/10/2024",
    status: "Pending",
    classLevel: "10",
    section: "A",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 8,
    studentName: "Wade Warren",
    classSection: "12 - A",
    bookTitle: "Jane Eyre",
    author: "Charlotte Brontë",
    issueDate: "07/10/2024",
    dueDate: "11/10/2024",
    status: "Return",
    classLevel: "12",
    section: "A",
    category: "Literature",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 9,
    studentName: "Marvin McKinney",
    classSection: "10 - D",
    bookTitle: "War and Peace",
    author: "Leo Tolstoy",
    issueDate: "08/10/2024",
    dueDate: "12/10/2024",
    status: "Pending",
    classLevel: "10",
    section: "D",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 10,
    studentName: "Cameron Williamson",
    classSection: "9 - B",
    bookTitle: "The Catcher in the Rye",
    author: "J.D. Salinger",
    issueDate: "09/10/2024",
    dueDate: "13/10/2024",
    status: "Return",
    classLevel: "9",
    section: "B",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 11,
    studentName: "Esther Howard",
    classSection: "11 - C",
    bookTitle: "Frankenstein",
    author: "Mary Shelley",
    issueDate: "10/10/2024",
    dueDate: "14/10/2024",
    status: "Pending",
    classLevel: "11",
    section: "C",
    category: "Science Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 12,
    studentName: "Jerome Bell",
    classSection: "12 - B",
    bookTitle: "The Odyssey",
    author: "Homer",
    issueDate: "11/10/2024",
    dueDate: "15/10/2024",
    status: "Return",
    classLevel: "12",
    section: "B",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 13,
    studentName: "Kathryn Murphy",
    classSection: "10 - C",
    bookTitle: "Brave New World",
    author: "Aldous Huxley",
    issueDate: "12/10/2024",
    dueDate: "16/10/2024",
    status: "Pending",
    classLevel: "10",
    section: "C",
    category: "Science Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 14,
    studentName: "Ethan Brown",
    classSection: "9 - A",
    bookTitle: "Wuthering Heights",
    author: "Emily Brontë",
    issueDate: "13/10/2024",
    dueDate: "17/10/2024",
    status: "Return",
    classLevel: "9",
    section: "A",
    category: "Literature",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 15,
    studentName: "Victoria Ortiz",
    classSection: "11 - D",
    bookTitle: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    issueDate: "14/10/2024",
    dueDate: "18/10/2024",
    status: "Pending",
    classLevel: "11",
    section: "D",
    category: "Fantasy",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 16,
    studentName: "Jacob Jones",
    classSection: "12 - D",
    bookTitle: "The Hobbit",
    author: "J.R.R. Tolkien",
    issueDate: "15/10/2024",
    dueDate: "19/10/2024",
    status: "Return",
    classLevel: "12",
    section: "D",
    category: "Fantasy",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 17,
    studentName: "Brooklyn Simmons",
    classSection: "10 - A",
    bookTitle: "A Tale of Two Cities",
    author: "Charles Dickens",
    issueDate: "16/10/2024",
    dueDate: "20/10/2024",
    status: "Pending",
    classLevel: "10",
    section: "A",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 18,
    studentName: "Aiden Nguyen",
    classSection: "9 - C",
    bookTitle: "Great Expectations",
    author: "Charles Dickens",
    issueDate: "17/10/2024",
    dueDate: "21/10/2024",
    status: "Return",
    classLevel: "9",
    section: "C",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 19,
    studentName: "Liam Martinez",
    classSection: "11 - A",
    bookTitle: "Fahrenheit 451",
    author: "Ray Bradbury",
    issueDate: "18/10/2024",
    dueDate: "22/10/2024",
    status: "Pending",
    classLevel: "11",
    section: "A",
    category: "Science Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
  {
    id: 20,
    studentName: "Avery Davis",
    classSection: "12 - C",
    bookTitle: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    issueDate: "19/10/2024",
    dueDate: "23/10/2024",
    status: "Paid",
    classLevel: "12",
    section: "C",
    category: "Classics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT19C_xDIFRmFMwPz1CZN_a5-ZP8sj_RPPB0Q&s",
  },
];